// Sector-aware rule pack registry. Drives ingestion extraction rules,
// model templates, fiscal calendar, macro variables and regulatory tags.

export interface SectorPack {
  sector: string;
  template: string;
  yearEnd: string;
  currency: string;
  ruleCount: number;
  macroVariables: string[];
  regulatoryTags: string[];
  sectorOverrides: string[]; // rule names that differ from the universal base
  baseRules: string[]; // representative universal rules (subset for the modal)
}

const UNIVERSAL_RULES: string[] = [
  "Revenue recognition timing",
  "Cost of goods sold mapping",
  "Operating expense classification",
  "Finance cost separation",
  "Tax expense reconciliation",
  "Earnings per share calculation",
  "Other comprehensive income mapping",
  "Property, plant & equipment additions",
  "Intangible asset amortisation",
  "Inventory valuation method",
  "Trade receivables ageing",
  "Trade payables ageing",
  "Cash & equivalents definition",
  "Short-term borrowings classification",
  "Long-term debt schedule",
  "Equity reconciliation",
  "Dividend declaration timing",
  "Related-party transactions disclosure",
  "Segment reporting basis",
  "Operating cash flow build",
  "Investing cash flow classification",
  "Financing cash flow classification",
  "Foreign exchange translation",
  "Contingent liabilities footnote",
  "Subsequent events tagging",
];

export const SECTOR_PACKS: Record<string, SectorPack> = {
  "Engineering & Industrials": {
    sector: "Engineering & Industrials",
    template: "MTL / Industrials template",
    yearEnd: "June 30",
    currency: "PKR thousands",
    ruleCount: 40,
    macroVariables: ["Tractor unit volumes", "Agri-implement sales", "KIBOR", "PKR/USD"],
    regulatoryTags: ["MEL merger restatement", "SECP industrial disclosure"],
    sectorOverrides: [
      "Tractor unit volume disaggregation",
      "IFS services revenue split",
      "MEL merger restatement tag",
      "Agri-implement sub-segment",
      "Allied Engineering income line",
      "Workshop receipts mapping",
      "Carriage outwards reclassification",
      "Service warranty provision",
      "Operating lease (machinery) note",
      "Bonus shares to employees",
      "Specie dividend treatment",
      "Government subsidy on tractors",
      "Spare parts inventory split",
      "Tractor finance scheme receivables",
      "Export rebate income",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  "Banking & Finance": {
    sector: "Banking & Finance",
    template: "Banking IFRS 9 template",
    yearEnd: "December 31",
    currency: "PKR thousands",
    ruleCount: 42,
    macroVariables: ["KIBOR", "ADR ratio", "SBP policy rate", "CPI", "PKR/USD"],
    regulatoryTags: ["IFRS 9 ECL provisioning", "Basel III capital", "Shariah compliance note"],
    sectorOverrides: [
      "Net interest income as revenue line",
      "ECL stage 1/2/3 provisioning",
      "Advances-to-deposits ratio (ADR)",
      "Capital adequacy ratio (CAR)",
      "Investments classification (HFT/AFS/HTM)",
      "Markup income recognition",
      "Non-funded income split",
      "Branch operating cost mapping",
      "Deposits maturity bucket",
      "Borrowings from SBP",
      "Shariah-compliant income note",
      "Risk-weighted assets calculation",
      "Pension fund actuarial gain",
      "Window takaful operations",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  "Oil & Gas": {
    sector: "Oil & Gas",
    template: "E&P sector template",
    yearEnd: "June 30",
    currency: "PKR thousands",
    ruleCount: 38,
    macroVariables: ["Gas well production (BCF)", "Brent crude (USD/bbl)", "Wellhead gas price", "PKR/USD"],
    regulatoryTags: ["OGRA petroleum policy", "PCA cost recovery", "Decommissioning provision"],
    sectorOverrides: [
      "Gas well production volumes",
      "Reserves disclosure (1P/2P/3P)",
      "Successful-efforts exploration accounting",
      "Decommissioning liability accretion",
      "Petroleum concession amortisation",
      "Royalty and excise duty",
      "Circular debt receivable",
      "Workover cost capitalisation",
      "Production-sharing agreement income",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  Fertilizers: {
    sector: "Fertilizers",
    template: "Fertilizer subsidy template",
    yearEnd: "December 31",
    currency: "PKR thousands",
    ruleCount: 36,
    macroVariables: ["Urea offtake (kt)", "DAP offtake (kt)", "Gas tariff", "GIDC", "Subsidy receivable"],
    regulatoryTags: ["GIDC adjustment", "Govt subsidy reconciliation"],
    sectorOverrides: [
      "Urea / DAP volume split",
      "Government subsidy receivable",
      "Gas tariff differential",
      "GIDC payable / adjustment",
      "Plant turnaround cost amortisation",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  "IT & Software": {
    sector: "IT & Software",
    template: "IT services template",
    yearEnd: "June 30",
    currency: "PKR thousands",
    ruleCount: 32,
    macroVariables: ["USD revenue %", "PKR/USD", "SBP export remittance", "Headcount"],
    regulatoryTags: ["PSEB export concession", "SECP listed-tech disclosure"],
    sectorOverrides: [
      "USD-denominated revenue translation",
      "Software licence amortisation",
      "Project WIP recognition",
      "Stock-based compensation",
      "Subsidiary reporting (NetSol US)",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  Pharmaceuticals: {
    sector: "Pharmaceuticals",
    template: "Pharma DRAP template",
    yearEnd: "December 31",
    currency: "PKR thousands",
    ruleCount: 34,
    macroVariables: ["DRAP price index", "API import cost", "PKR/USD", "CPI healthcare"],
    regulatoryTags: ["DRAP pricing", "Generic vs branded split"],
    sectorOverrides: [
      "DRAP pricing notification adjustment",
      "API import cost pass-through",
      "R&D capitalisation",
      "Generic vs branded revenue split",
      "Free-sample marketing expense",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  "Food & FMCG": {
    sector: "Food & FMCG",
    template: "FMCG distribution template",
    yearEnd: "December 31",
    currency: "PKR thousands",
    ruleCount: 35,
    macroVariables: ["CPI food", "Distributor margin", "PKR/USD", "Wheat / sugar / milk index"],
    regulatoryTags: ["PFA compliance", "Excise / FED on beverages"],
    sectorOverrides: [
      "Trade discount netting",
      "Distributor incentive accrual",
      "Brand advertising expense",
      "Cold-chain logistics cost",
      "Federal excise duty on beverages",
    ],
    baseRules: UNIVERSAL_RULES,
  },
  Textiles: {
    sector: "Textiles",
    template: "Textile vertically-integrated template",
    yearEnd: "June 30",
    currency: "PKR thousands",
    ruleCount: 37,
    macroVariables: ["Cotton price (PKR/maund)", "USD revenue %", "Energy tariff", "PKR/USD"],
    regulatoryTags: ["DLTL export rebate", "Energy subsidy"],
    sectorOverrides: [
      "Cotton inventory NRV adjustment",
      "Spinning / weaving / processing split",
      "DLTL export rebate accrual",
      "Energy tariff differential",
      "Captive power generation cost",
    ],
    baseRules: UNIVERSAL_RULES,
  },
};

export function getSectorPack(sector: string): SectorPack {
  return SECTOR_PACKS[sector] ?? SECTOR_PACKS["Engineering & Industrials"];
}
