/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SignOffRouteImport } from './routes/sign-off'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DiffReviewRouteImport } from './routes/diff-review'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssumptionsRouteImport } from './routes/assumptions'
import { Route as IndexRouteImport } from './routes/index'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOffRoute = SignOffRouteImport.update({
  id: '/sign-off',
  path: '/sign-off',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffReviewRoute = DiffReviewRouteImport.update({
  id: '/diff-review',
  path: '/diff-review',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssumptionsRoute = AssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/audit': typeof AuditRoute
  '/diagnosis': typeof DiagnosisRoute
  '/diff-review': typeof DiffReviewRoute
  '/forecast': typeof ForecastRoute
  '/inbox': typeof InboxRoute
  '/ingestion': typeof IngestionRoute
  '/notifications': typeof NotificationsRoute
  '/protection': typeof ProtectionRoute
  '/registry': typeof RegistryRoute
  '/review': typeof ReviewRoute
  '/sign-off': typeof SignOffRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/audit': typeof AuditRoute
  '/diagnosis': typeof DiagnosisRoute
  '/diff-review': typeof DiffReviewRoute
  '/forecast': typeof ForecastRoute
  '/inbox': typeof InboxRoute
  '/ingestion': typeof IngestionRoute
  '/notifications': typeof NotificationsRoute
  '/protection': typeof ProtectionRoute
  '/registry': typeof RegistryRoute
  '/review': typeof ReviewRoute
  '/sign-off': typeof SignOffRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/audit': typeof AuditRoute
  '/diagnosis': typeof DiagnosisRoute
  '/diff-review': typeof DiffReviewRoute
  '/forecast': typeof ForecastRoute
  '/inbox': typeof InboxRoute
  '/ingestion': typeof IngestionRoute
  '/notifications': typeof NotificationsRoute
  '/protection': typeof ProtectionRoute
  '/registry': typeof RegistryRoute
  '/review': typeof ReviewRoute
  '/sign-off': typeof SignOffRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assumptions'
    | '/audit'
    | '/diagnosis'
    | '/diff-review'
    | '/forecast'
    | '/inbox'
    | '/ingestion'
    | '/notifications'
    | '/protection'
    | '/registry'
    | '/review'
    | '/sign-off'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assumptions'
    | '/audit'
    | '/diagnosis'
    | '/diff-review'
    | '/forecast'
    | '/inbox'
    | '/ingestion'
    | '/notifications'
    | '/protection'
    | '/registry'
    | '/review'
    | '/sign-off'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/assumptions'
    | '/audit'
    | '/diagnosis'
    | '/diff-review'
    | '/forecast'
    | '/inbox'
    | '/ingestion'
    | '/notifications'
    | '/protection'
    | '/registry'
    | '/review'
    | '/sign-off'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssumptionsRoute: typeof AssumptionsRoute
  AuditRoute: typeof AuditRoute
  DiagnosisRoute: typeof DiagnosisRoute
  DiffReviewRoute: typeof DiffReviewRoute
  ForecastRoute: typeof ForecastRoute
  InboxRoute: typeof InboxRoute
  IngestionRoute: typeof IngestionRoute
  NotificationsRoute: typeof NotificationsRoute
  ProtectionRoute: typeof ProtectionRoute
  RegistryRoute: typeof RegistryRoute
  ReviewRoute: typeof ReviewRoute
  SignOffRoute: typeof SignOffRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-off': {
      id: '/sign-off'
      path: '/sign-off'
      fullPath: '/sign-off'
      preLoaderRoute: typeof SignOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff-review': {
      id: '/diff-review'
      path: '/diff-review'
      fullPath: '/diff-review'
      preLoaderRoute: typeof DiffReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assumptions': {
      id: '/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AssumptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssumptionsRoute: AssumptionsRoute,
  AuditRoute: AuditRoute,
  DiagnosisRoute: DiagnosisRoute,
  DiffReviewRoute: DiffReviewRoute,
  ForecastRoute: ForecastRoute,
  InboxRoute: InboxRoute,
  IngestionRoute: IngestionRoute,
  NotificationsRoute: NotificationsRoute,
  ProtectionRoute: ProtectionRoute,
  RegistryRoute: RegistryRoute,
  ReviewRoute: ReviewRoute,
  SignOffRoute: SignOffRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
